### PR TITLE
switch default locale to utf8

### PR DESCRIPTION
**Pull request by smelchior**
*Issue:*
Currently the Image uses `POSIX` as the default locale, which caused issues for us when switching from the openjdk image. The openjdk image uses `C.UTF-8` as the default locale which makes more sense as a sane default.

*Description of changes:*
Switches the default locale to utf-8 for the container

### CODE REVIEW

**Comment by EricEdens** [comment]
Nice! [docker-library's #32](https://github.com/docker-library/openjdk/issues/32) provides background on this issue.

Some questions:

@smelchior : 
  - Can you write some tests to make sure that this behaves correctly now and into the future?
  - I only see `LANG` in [openjdk's Dockerfile](https://github.com/docker-library/openjdk/blob/master/8/jdk/Dockerfile). Any reason that we need `LC_ALL`?

@ilianaw :
  - Any thoughts on putting this in the AL2 base image instead of here?

**Comment by smelchior** [comment]
Thanks for the quick response @EricEdens 👍 
I did some tests, LANG is sufficient for the JDK, so i removed LC_ALL. 
A test for the env var has also been added.

**Comment by iliana** [comment]
> Any thoughts on putting this in the AL2 base image instead of here?

<s>Probably not a good idea since we install the glibc-minimal-langpack.</s> wait C.utf-8 is totally a thing in the minimal langpack

I'm not particularly inclined to change our default since the base image has been out for a year? I should discuss it with the team and look at some other base images.

**Comment by iliana** [comment]
Most other base images don't have any special locales set, so I'll propose that putting it in this image is more correct.

**Comment by EricEdens** [comment]
Thanks @ilianaw :)

@smelchior, looks good! Go ahead and squash your commits and then I'll merge it.

**Comment by smelchior** [comment]
sure, squash is done

**Review by EricEdens — APPROVED** [review]
thanks!

**Comment by smelchior** [comment]
nice :) what is the release process for the images on docker hub?

**Comment by iliana** [comment]
> what is the release process for the images on docker hub?

One of the maintainers updates [this file](https://github.com/docker-library/official-images/blob/master/library/amazoncorretto) and then the Docker Library project's builders build and publish the image.

**Pull request merged**
